name: Tests

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/checks.yml
